// ARDUINO BRIDGE HEADER - Generated by Lamia v0.3.0
#pragma once
#include <string>

namespace ArduinoBridge {
    class LamiaTranspiler {
    public:
        bool initialize(const std::string& board_type);
        std::string transpile_to_arduino(const std::string& lamia_code);
        bool optimize_for_microcontroller(std::string& code, const std::string& mcu_type);
    };
}
