// CNC BRIDGE HEADER - Generated by Lamia v0.3.0
#pragma once
#include <string>
#include <vector>

namespace CNCBridge {
    class ZCodeConverter {
    public:
        bool initialize();
        bool convert_gcode_to_zcode(const std::string& input, std::string& output);
        bool process_machining_commands(const std::vector<std::string>& commands);
    };
}
