// IOT BRIDGE HEADER - Generated by Lamia v0.3.0
#pragma once
#include <string>
#include <vector>

namespace IoTBridge {
    struct SensorData {
        std::string id;
        double value;
        long timestamp;
    };

    class IoTFramework {
    public:
        bool initialize();
        bool register_sensor(const std::string& id, const std::string& type);
        SensorData read_sensor(const std::string& id);
        bool send_to_cloud(const SensorData& data);
    };
}
